### ISSUE TITLE
Création des emploi du temps

### ISSUE THREAD

**Issue by jf-jung** [ItechSup/itechSIS#11]
Il me faut un écran pour la création des Events.
Cet écran doit être accessible depuis la page de détail d'une session.
Il doit être possible d'ajouter des événements hebdomadaires récurrents, c'est à dire par exemple de choisir un jour de la semaine, un horaire de début ainsi qu'un horaire de fin, puis que le système créé les événements associés sur toute la durée de la session.

**Comment by Dinaam** [comment]
Je suis totalement perdu pour le code du Session.controller

**Comment by wtmaxim** [comment]
Pour la création des events, il y avait un problème avec le formulaire qui était dans session/id/event.
Pour le corriger, le formulaire dans /event/new a été enlevé car il est plus simple de créer un event à partir de la session.

**Comment by jf-jung** [comment]
Bien joué !
