### ISSUE TITLE
Planning Ecole

### ISSUE THREAD

**Issue by jf-jung** [ItechSup/itechSIS#13]
Il me faut une entité School à laquelle on rattache : 
* les Room (ManyToMany)
* les Formation (ManyToOne)
* les Teacher (ManyToMany)
avec les attributs suivants:
* un nom
* une heure d'ouverture
* une heure de fermeture
* une collection de jours de fermeture -> créer une Entity pour les jours de fermeture

**Comment by jf-jung** [comment]
Pour les jours de fermeture, il faut une date et aussi un motif

**Comment by jf-jung** [comment]
J'ai jeté un coup d'oeil, les relations entre entities c'est n'importe quoi, il faut corriger ça !

**Comment by Dinaam** [comment]
La relation entre school et room n'est pas une ManyToOne? Idem entre teacher et School? Il y a une seule école non?

**Comment by Dinaam** [comment]
J'ai corriger les relations mais je peux pas update ma base à cause des contraintes de clé étrangère et je ne comprend pas pourquoi

**Comment by jf-jung** [comment]
Surement a cause des données déjà présentes. drop ton schema actuel avant de créer le nouveau

**Comment by Dinaam** [comment]
C'était ça, merci !

**Comment by Dinaam** [comment]
On ne peut plus créer de formation puisque maintenant on a besoin du School ID et même en rajoutant un champ pour mettre l'école ce n'est pas possible

**Comment by jf-jung** [comment]
Effectivement, il manque setSchool() sur Formation...

**Comment by Dinaam** [comment]
Fait

**Comment by jf-jung** [comment]
N'hésite pas à push, j'ai rien là
