### ISSUE TITLE
Génération des feuilles de présence

### ISSUE THREAD

**Issue by jf-jung** [ItechSup/itechSIS#14]
Nous avons besoin de deux type de feuille d'émargement:
* Une feuille individuelle et mensuelle:
** Afficher deux cases de signature (une pour le prof, une pour l'élève) par demi-journée où la présence est requise (ie un Event concerne l'élève ce jour là)
** Afficher en regard la date
** Afficher le nombre total d'heure de formation prévu pour l'élève sur le mois

* Une feuille de présence quotidienne:
** Par session,
** si elle est associée à des Events ce jour-là.
** Elle reprend la liste des élèves
** et propose 4 case à signer par élève
** et 4 cases pour les profs

**Comment by wtmaxim** [comment]
Terminé.

**Comment by jf-jung** [comment]
Mergé
