### ISSUE TITLE
Contrainte de clé

### ISSUE THREAD

**Issue by wtmaxim** [ItechSup/itechSIS#17]
Pour les bouttons "delete", je ne vois pas comment gérer les contraintes de clés étrangères sauf celle de session que j'ai réussis.

**Comment by jf-jung** [comment]
Il me faut plus détails.

**Comment by wtmaxim** [comment]
Pour les sessions, j'ai fais ce code-ci qui fonctionne
{% if entity.formation == "" %}
      {{ form(delete_form) }}
{% endif %}

Seulement, pour le reste, je ne vois pas comment faire car par exemple pour une "room", si on ne la met dans dans un event, à aucun moment on ne sait-ci celle ci est utilisé ou non.

**Comment by wtmaxim** [comment]
Comment faire pour enlever les bouttons delete quand ils ne sont pas utiles ?
