### ISSUE TITLE
Inscription des étudiants

### ISSUE THREAD

**Issue by jf-jung** [ItechSup/itechSIS#3]
Il faudrait un nouvel écran pour inscrire des étudiants à une session.

**Comment by jf-jung** [comment]
Un nouvel écran avec un lien dans le menu ;)

**Comment by jf-jung** [comment]
Sur cet écran il faut pouvoir :
1. Choisir une session de formation
2. Afficher les élèves inscrits à cette session
3. Choisir les élèves associés à cette formation parmi ceux qui ne sont pas encore inscrits
4. Retirer des élèves inscrits à cette session de la liste

**Comment by Dinaam** [comment]
J'aimerais savoir ou doit apparaître les élèves non inscrits (petit 3)

**Comment by jf-jung** [comment]
Sur l'écran en question :p
